#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(binding = 0) uniform usampler3D uSrcOcc;
layout(binding = 1, r8ui) uniform uimage3D uDstOcc;

void main()
{
    ivec3 dst = ivec3(gl_GlobalInvocationID.xyz);
    ivec3 dstDims = imageSize(uDstOcc);
    if (any(greaterThanEqual(dst, dstDims)))
    {
        return;
    }

    ivec3 srcDims = textureSize(uSrcOcc, 0);
    ivec3 base = dst * 2;
    uint occ = 0u;

    for (int z = 0; z < 2; ++z)
    {
        for (int y = 0; y < 2; ++y)
        {
            for (int x = 0; x < 2; ++x)
            {
                ivec3 src = base + ivec3(x, y, z);
                if (all(lessThan(src, srcDims)))
                {
                    occ |= texelFetch(uSrcOcc, src, 0).r;
                }
            }
        }
    }

    imageStore(uDstOcc, dst, uvec4(occ, 0u, 0u, 0u));
}
